# This is a basic workflow to help you get started with Actions

name: Addition

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [main]
jobs:
  job1 :  
    name : addition
    runs-on : ubuntu-latest
    steps:
      - name: Addition of 2 and 4
        shell: bash
        run: |
          expr 2 + 4 > AddBook.txt
      - name  : upload AddResult for job1
        uses: actions/upload-artifact@v2
        with :
          name: Book1
          path : AddBook.txt 
          
